# Generated by Django 6.0.4 on 2026-04-29 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TranstornosMentais',
            fields=[
                ('id', models.BigAutoField(help_text='Chave primária do registro', primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Código de identificação do registro', max_length=10, verbose_name='Código')),
                ('created_date', models.DateTimeField(auto_now_add=True, help_text='Timestamp de criação do registro', verbose_name='Data de criação')),
                ('created_by', models.CharField(help_text='Usuário que criou o registro', max_length=256, verbose_name='Criado por')),
                ('last_modified_date', models.DateTimeField(auto_now=True, help_text='Timestamp da última modificação do registro', verbose_name='Data de última modificação')),
                ('last_modified_by', models.CharField(help_text='Usuário que realizou a última modificação', max_length=256, verbose_name='Modificado por')),
                ('status', models.CharField(help_text='Status do registro', max_length=20, verbose_name='Status')),
                ('co_cbo_ocupacao', models.CharField(help_text='Ocupação do indivíduo que sofreu o agravo.', max_length=6, verbose_name='Ocupação (CBO)')),
                ('tp_mercado_trabalho', models.CharField(blank=True, choices=[('01', 'Empregado registrado com carteira assinada'), ('02', 'Empregado não registrado'), ('03', 'Autônomo/conta própria'), ('04', 'Servidor público estatutário'), ('05', 'Servidor público celetista'), ('06', 'Aposentado'), ('07', 'Desempregado'), ('08', 'Trabalho temporário'), ('09', 'Cooperativado'), ('10', 'Trabalhador avulso'), ('11', 'Empregador'), ('12', 'Outros'), ('99', 'Ignorado')], help_text='Situação de trabalho do indivíduo que sofreu o agravo.', max_length=2, null=True, verbose_name='Situação no mercado de trabalho')),
                ('nu_tempo_trabalho', models.CharField(blank=True, help_text='Quantidade de tempo trabalhado na ocupação.', max_length=2, null=True, verbose_name='Tempo de trabalho na ocupação')),
                ('tp_tempo_trabalho', models.CharField(blank=True, choices=[('1', 'Hora'), ('2', 'Dias'), ('3', 'Meses'), ('4', 'Anos')], help_text='Unidade de medida do tempo de trabalho.', max_length=1, null=True, verbose_name='Unidade de tempo')),
                ('nu_cnpj_cpf', models.CharField(blank=True, help_text='Número de registro/CNPJ ou CPF do contratante.', max_length=18, null=True, verbose_name='CNPJ/CPF do contratante')),
                ('no_empresa', models.CharField(blank=True, help_text='Nome da empresa ou empregador contratante.', max_length=70, null=True, verbose_name='Nome da empresa ou empregador')),
                ('co_cnae', models.CharField(blank=True, help_text='Classificação Nacional da Atividade Econômica do Contratante.', max_length=10, null=True, verbose_name='CNAE')),
                ('co_uf_empresa', models.CharField(blank=True, help_text='Unidade de Federação da empresa contratante.', max_length=2, null=True, verbose_name='UF da empresa')),
                ('co_municipio_empresa', models.CharField(blank=True, help_text='Município da empresa contratante.', max_length=6, null=True, verbose_name='Município da empresa')),
                ('co_distrito_empresa', models.CharField(blank=True, help_text='Código do distrito da empresa contratante.', max_length=4, null=True, verbose_name='Distrito da empresa')),
                ('no_distrito_empresa', models.CharField(blank=True, help_text='Nome do distrito da empresa contratante.', max_length=70, null=True, verbose_name='Nome do distrito da empresa')),
                ('co_bairro_empresa', models.CharField(blank=True, help_text='Código do bairro da empresa contratante.', max_length=8, null=True, verbose_name='Código do bairro da empresa')),
                ('no_bairro_empresa', models.CharField(blank=True, help_text='Nome do bairro da empresa contratante.', max_length=60, null=True, verbose_name='Bairro da empresa')),
                ('co_endereco_empresa', models.CharField(blank=True, help_text='Código do endereço da empresa contratante.', max_length=60, null=True, verbose_name='Código do endereço da empresa')),
                ('no_endereco_empresa', models.CharField(blank=True, help_text='Endereço da empresa contratante.', max_length=60, null=True, verbose_name='Endereço da empresa')),
                ('nu_numero_empresa', models.CharField(blank=True, help_text='Número do lote da empresa contratante.', max_length=6, null=True, verbose_name='Número da empresa')),
                ('no_referencia_empresa', models.CharField(blank=True, help_text='Ponto de referência da empresa contratante.', max_length=70, null=True, verbose_name='Ponto de referência da empresa')),
                ('ds_ddd_empresa', models.CharField(blank=True, help_text='DDD do telefone da empresa contratante.', max_length=3, null=True, verbose_name='DDD da empresa')),
                ('ds_telefone_empresa', models.CharField(blank=True, help_text='Telefone da empresa contratante.', max_length=8, null=True, verbose_name='Telefone da empresa')),
                ('tp_empresa_terceirizada', models.CharField(blank=True, choices=[('1', 'Sim'), ('2', 'Não'), ('3', 'Não se aplica'), ('9', 'Ignorado')], help_text='O empregador é de alguma empresa terceirizada.', max_length=2, null=True, verbose_name='Empregador é empresa terceirizada')),
                ('nu_tempo_exposicao_risco', models.CharField(blank=True, help_text='Quantidade de tempo de exposição ao agente de risco.', max_length=2, null=True, verbose_name='Tempo de exposição ao agente de risco')),
                ('tp_tempo_exposicao_risco', models.CharField(blank=True, choices=[('H', 'Hora'), ('D', 'Dias'), ('M', 'Meses'), ('A', 'Anos')], help_text='Unidade de medida do tempo de exposição.', max_length=1, null=True, verbose_name='Unidade de tempo de exposição')),
                ('st_regime_tratamento', models.CharField(blank=True, choices=[('1', 'Hospitalar'), ('2', 'Ambulatorial')], help_text='Regime de tratamento (hospitalar ou ambulatorial).', max_length=1, null=True, verbose_name='Regime de tratamento')),
                ('co_cid_diagnostico', models.CharField(help_text='Diagnóstico específico - CID 10.', max_length=4, verbose_name='CID-10 do diagnóstico')),
                ('st_habito_alcool', models.CharField(blank=True, choices=[('1', 'Sim'), ('2', 'Não'), ('9', 'Ignorado')], help_text='Hábito do paciente de uso de álcool.', max_length=1, null=True, verbose_name='Hábito - Álcool')),
                ('st_habito_psicoativas', models.CharField(blank=True, choices=[('1', 'Sim'), ('2', 'Não'), ('9', 'Ignorado')], help_text='Hábito do paciente de uso de drogas psicoativas.', max_length=1, null=True, verbose_name='Hábito - Drogas psicoativas')),
                ('st_habito_psicofarmacos', models.CharField(blank=True, choices=[('1', 'Sim'), ('2', 'Não'), ('9', 'Ignorado')], help_text='Hábito do paciente de uso de psicofármacos.', max_length=1, null=True, verbose_name='Hábito - Psicofármacos')),
                ('tp_habito_fumar', models.CharField(blank=True, choices=[('1', 'Sim'), ('2', 'Não'), ('3', 'Ex-fumante'), ('9', 'Ignorado')], help_text='Se o paciente possui o hábito de fumar.', max_length=1, null=True, verbose_name='Hábito de fumar')),
                ('nu_tempo_exposicao_tabaco', models.CharField(blank=True, help_text='Quantidade de tempo de exposição ao tabaco.', max_length=2, null=True, verbose_name='Tempo de exposição ao tabaco')),
                ('tp_tempo_exposicao_tabaco', models.CharField(blank=True, choices=[('1', 'Hora'), ('2', 'Dia'), ('3', 'Mês'), ('4', 'Ano')], help_text='Unidade de medida do tempo de exposição ao tabaco.', max_length=1, null=True, verbose_name='Unidade de tempo - Exposição ao tabaco')),
                ('st_conduta_afasta_desgaste', models.CharField(blank=True, choices=[('1', 'Sim'), ('2', 'Não')], help_text='Afastamento da situação de desgaste mental.', max_length=1, null=True, verbose_name='Conduta - Afastamento da situação de desgaste mental')),
                ('st_conduta_protecao_individual', models.CharField(blank=True, choices=[('1', 'Sim'), ('2', 'Não')], help_text='Adoção de proteção individual.', max_length=1, null=True, verbose_name='Conduta - Proteção individual')),
                ('st_conduta_mudanca_trabalho', models.CharField(blank=True, choices=[('1', 'Sim'), ('2', 'Não')], help_text='Adoção de mudança na organização do trabalho.', max_length=1, null=True, verbose_name='Conduta - Mudança na organização do trabalho')),
                ('st_conduta_nenhum', models.CharField(blank=True, choices=[('1', 'Sim'), ('2', 'Não')], help_text='Nenhuma atitude tomada em relação ao agravo.', max_length=1, null=True, verbose_name='Conduta - Nenhuma')),
                ('st_conduta_protecao_coletiva', models.CharField(blank=True, choices=[('1', 'Sim'), ('2', 'Não')], help_text='Adoção de proteção coletiva.', max_length=1, null=True, verbose_name='Conduta - Proteção coletiva')),
                ('st_conduta_afasta_trabalho', models.CharField(blank=True, choices=[('1', 'Sim'), ('2', 'Não')], help_text='Afastamento do local de trabalho.', max_length=1, null=True, verbose_name='Conduta - Afastamento do local de trabalho')),
                ('st_conduta_outro', models.CharField(blank=True, choices=[('1', 'Sim'), ('2', 'Não')], help_text='Outras atitudes tomadas em relação ao agravo.', max_length=1, null=True, verbose_name='Conduta - Outros')),
                ('ds_conduta_outro', models.CharField(blank=True, help_text='Especificação quando conduta outro = 1 (Sim).', max_length=30, null=True, verbose_name='Outras condutas (especificar)')),
                ('st_trabalhador_mesma_doenca', models.CharField(blank=True, choices=[('1', 'Sim'), ('2', 'Não'), ('9', 'Ignorado')], help_text='Se outros trabalhadores sofreram ou não o mesmo agravo no local de trabalho.', max_length=1, null=True, verbose_name='Outros trabalhadores com a mesma doença')),
                ('st_paciente_capes', models.CharField(blank=True, choices=[('1', 'Sim'), ('2', 'Não'), ('9', 'Ignorado')], help_text='Se o paciente foi encaminhado a um CAPS ou outro serviço especializado em tratamento de transtornos mentais.', max_length=1, null=True, verbose_name='Encaminhamento a CAPS')),
                ('tp_evolucao_caso', models.CharField(blank=True, choices=[('1', 'Cura'), ('2', 'Cura não confirmada'), ('3', 'Incapacidade temporária'), ('4', 'Incapacidade permanente parcial'), ('5', 'Incapacidade permanente total'), ('6', 'Óbito por doença relacionada ao trabalho'), ('7', 'Óbito por outra causa'), ('8', 'Outro'), ('9', 'Ignorado')], help_text='Evolução da situação do paciente.', max_length=1, null=True, verbose_name='Evolução do caso')),
                ('dt_obito', models.DateField(blank=True, help_text='Data do óbito. Obrigatório se evolução = 6 ou 7. Deve ser >= data do diagnóstico.', null=True, verbose_name='Data do óbito')),
                ('tp_comunicacao_cat', models.CharField(choices=[('1', 'Sim'), ('2', 'Não'), ('3', 'Não se aplica'), ('9', 'Ignorado')], help_text='Se foi emitida a comunicação de acidente do trabalho (CAT).', max_length=1, verbose_name='Comunicação de Acidente de Trabalho - CAT')),
                ('nu_lote_vertical', models.CharField(blank=True, help_text='Identificador do lote de transferência vertical da investigação entre níveis do sistema.', max_length=7, null=True, verbose_name='Lote de transferência vertical')),
            ],
            options={
                'verbose_name': 'Transtornos Mentais Relacionados ao Trabalho',
                'verbose_name_plural': 'Transtornos Mentais Relacionados ao Trabalho',
                'db_table': 'transtornos_mentais',
                'ordering': ['-created_date'],
            },
        ),
    ]
