# Generated by Django 6.0.4 on 2026-04-29 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcidenteTrabalhoGrave',
            fields=[
                ('id', models.BigAutoField(help_text='Chave primária do registro', primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Código de identificação do registro', max_length=10, verbose_name='Código')),
                ('created_date', models.DateTimeField(auto_now_add=True, help_text='Timestamp de criação do registro', verbose_name='Data de criação')),
                ('created_by', models.CharField(help_text='Usuário que criou o registro', max_length=256, verbose_name='Criado por')),
                ('last_modified_date', models.DateTimeField(auto_now=True, help_text='Timestamp da última modificação do registro', verbose_name='Data de última modificação')),
                ('last_modified_by', models.CharField(help_text='Usuário que realizou a última modificação', max_length=256, verbose_name='Modificado por')),
                ('status', models.CharField(help_text='Status do registro', max_length=20, verbose_name='Status')),
                ('co_cbo_ocupacao', models.CharField(help_text='Ocupação do indivíduo que sofreu o agravo.', max_length=6, verbose_name='Ocupação (CBO)')),
                ('tp_mercado_trabalho', models.CharField(blank=True, choices=[('01', 'Empregado registrado com carteira assinada'), ('02', 'Empregado não registrado'), ('03', 'Autônomo/conta própria'), ('04', 'Servidor público estatutário'), ('05', 'Servidor público celetista'), ('06', 'Aposentado'), ('07', 'Desempregado'), ('08', 'Trabalho temporário'), ('09', 'Cooperativado'), ('10', 'Trabalhador avulso'), ('11', 'Empregador'), ('12', 'Outros'), ('99', 'Ignorado')], help_text='Situação de trabalho do indivíduo que sofreu o agravo.', max_length=2, null=True, verbose_name='Situação no mercado de trabalho')),
                ('nu_tempo_trabalho', models.SmallIntegerField(blank=True, help_text='Quantidade de tempo trabalhado na ocupação.', null=True, verbose_name='Tempo de trabalho na ocupação')),
                ('tp_tempo_trabalho', models.CharField(blank=True, choices=[('1', 'Hora'), ('2', 'Dias'), ('3', 'Meses'), ('4', 'Anos')], help_text='Unidade de medida do tempo de trabalho.', max_length=1, null=True, verbose_name='Unidade de tempo')),
                ('tp_local_acidente', models.CharField(choices=[('1', 'Instalações do Contratante'), ('2', 'Via Pública'), ('3', 'Instalações de terceiros'), ('4', 'Domicílio próprio'), ('9', 'Ignorado')], help_text='Local onde ocorreu o acidente.', max_length=1, verbose_name='Local onde ocorreu o acidente')),
                ('nu_cnpj_cpf', models.CharField(blank=True, help_text='Número de registro/CNPJ ou CPF do contratante.', max_length=18, null=True, verbose_name='CNPJ/CPF do contratante')),
                ('no_empresa', models.CharField(blank=True, help_text='Nome da empresa ou empregador contratante.', max_length=70, null=True, verbose_name='Nome da empresa ou empregador')),
                ('co_cnae', models.CharField(blank=True, help_text='Classificação Nacional da Atividade Econômica do Contratante.', max_length=10, null=True, verbose_name='CNAE')),
                ('co_uf_empresa', models.CharField(blank=True, help_text='Unidade da Federação da empresa contratante.', max_length=2, null=True, verbose_name='UF da empresa')),
                ('co_municipio_empresa', models.CharField(blank=True, help_text='Município da empresa contratante.', max_length=6, null=True, verbose_name='Município da empresa')),
                ('co_distrito_empresa', models.CharField(blank=True, help_text='Distrito da empresa contratante.', max_length=9, null=True, verbose_name='Distrito da empresa')),
                ('no_distrito_empresa', models.CharField(blank=True, help_text='Nome do distrito da empresa contratante.', max_length=70, null=True, verbose_name='Nome do distrito da empresa')),
                ('co_bairro_empresa', models.CharField(blank=True, help_text='Código do bairro da empresa contratante.', max_length=8, null=True, verbose_name='Código do bairro da empresa')),
                ('no_bairro_empresa', models.CharField(blank=True, help_text='Bairro da empresa contratante.', max_length=70, null=True, verbose_name='Bairro da empresa')),
                ('co_endereco_empresa', models.CharField(blank=True, help_text='Código do endereço da empresa contratante.', max_length=60, null=True, verbose_name='Código do endereço da empresa')),
                ('no_endereco_empresa', models.CharField(blank=True, help_text='Endereço da empresa contratante.', max_length=60, null=True, verbose_name='Endereço da empresa')),
                ('nu_numero_empresa', models.CharField(blank=True, help_text='Número do lote da empresa contratante.', max_length=6, null=True, verbose_name='Número do endereço da empresa')),
                ('no_referencia_empresa', models.CharField(blank=True, help_text='Ponto de referência da empresa contratante.', max_length=70, null=True, verbose_name='Ponto de referência da empresa')),
                ('nu_ddd_empresa', models.CharField(blank=True, help_text='DDD do telefone da empresa contratante.', max_length=3, null=True, verbose_name='DDD da empresa')),
                ('nu_telefone_empresa', models.CharField(blank=True, help_text='Telefone da empresa contratante.', max_length=9, null=True, verbose_name='Telefone da empresa')),
                ('tp_empresa_terceirizada', models.CharField(blank=True, choices=[('1', 'Sim'), ('2', 'Não'), ('3', 'Não se aplica'), ('9', 'Ignorado')], help_text='O empregador é de alguma empresa terceirizada.', max_length=2, null=True, verbose_name='Empregador é empresa terceirizada')),
                ('co_cnae_principal', models.CharField(blank=True, help_text='CNAE da empresa terceirizadora/principal.', max_length=10, null=True, verbose_name='CNAE da empresa principal')),
                ('nu_cnpj_principal', models.CharField(blank=True, help_text='CNPJ da empresa principal (terceirizadora).', max_length=18, null=True, verbose_name='CNPJ da empresa principal')),
                ('no_razao_social_principal', models.CharField(blank=True, help_text='Nome da empresa principal (terceirizadora).', max_length=70, null=True, verbose_name='Razão social da empresa principal')),
                ('nu_hr_acidente', models.CharField(blank=True, help_text='Hora em que ocorreu o acidente.', max_length=2, null=True, verbose_name='Hora do acidente')),
                ('nu_minuto_acidente', models.CharField(blank=True, help_text='Minutos em que ocorreu o acidente.', max_length=2, null=True, verbose_name='Minutos do acidente')),
                ('nu_hr_inicio_jornada', models.CharField(blank=True, help_text='Horas decorridas após o início da jornada de trabalho.', max_length=2, null=True, verbose_name='Horas após início da jornada')),
                ('nu_minuto_inicio_jornada', models.CharField(blank=True, help_text='Minutos decorridos após o início da jornada de trabalho.', max_length=2, null=True, verbose_name='Minutos após início da jornada')),
                ('co_uf_acidente', models.CharField(blank=True, help_text='Unidade Federativa do local do acidente.', max_length=2, null=True, verbose_name='UF do local do acidente')),
                ('co_municipio_acidente', models.CharField(blank=True, help_text='Município onde ocorreu o acidente.', max_length=6, null=True, verbose_name='Município de ocorrência do acidente')),
                ('co_cid_causa_acidente', models.CharField(help_text='Código CID-10 da causa do acidente (V01 a Y98).', max_length=4, verbose_name='CID-10 da causa do acidente')),
                ('tp_acidente', models.CharField(blank=True, choices=[('1', 'Típico'), ('2', 'Trajeto'), ('9', 'Ignorado')], help_text='Tipo de acidente (típico ou trajeto).', max_length=1, null=True, verbose_name='Tipo de acidente')),
                ('st_trabalhador_atingido_outro', models.CharField(blank=True, choices=[('1', 'Sim'), ('2', 'Não'), ('9', 'Ignorado')], help_text='Se outros trabalhadores foram atingidos pelo acidente.', max_length=1, null=True, verbose_name='Houve outros trabalhadores atingidos')),
                ('nu_trabalhador_atingido', models.CharField(blank=True, help_text='Quantidade de outros trabalhadores atingidos.', max_length=3, null=True, verbose_name='Número de trabalhadores atingidos')),
                ('st_atendimento_medico', models.CharField(blank=True, choices=[('1', 'Sim'), ('2', 'Não'), ('9', 'Ignorado')], help_text='Se ocorreu atendimento médico ao acidentado.', max_length=1, null=True, verbose_name='Ocorreu atendimento médico')),
                ('dt_atendimento', models.DateField(blank=True, help_text='Data do atendimento médico.', null=True, verbose_name='Data do atendimento')),
                ('co_uf_atendimento', models.CharField(blank=True, help_text='Unidade Federativa do local do atendimento.', max_length=2, null=True, verbose_name='UF do atendimento')),
                ('co_municipio_atendimento', models.CharField(blank=True, help_text='Município onde ocorreu o atendimento.', max_length=6, null=True, verbose_name='Município do atendimento')),
                ('co_unidade_atendimento', models.CharField(blank=True, help_text='Código da unidade de saúde de atendimento.', max_length=7, null=True, verbose_name='Código da unidade de atendimento')),
                ('tp_parte_corpo_1', models.CharField(blank=True, choices=[('01', 'Olho'), ('02', 'Cabeça'), ('03', 'Pescoço'), ('04', 'Tórax'), ('05', 'Abdome'), ('06', 'Mão'), ('07', 'Membro superior'), ('08', 'Membro inferior'), ('09', 'Pé'), ('10', 'Todo o corpo'), ('11', 'Outro'), ('99', 'Ignorado')], help_text='Parte do corpo atingida no acidente - 1ª ocorrência.', max_length=2, null=True, verbose_name='Parte do corpo atingida 1')),
                ('tp_parte_corpo_2', models.CharField(blank=True, choices=[('01', 'Olho'), ('02', 'Cabeça'), ('03', 'Pescoço'), ('04', 'Tórax'), ('05', 'Abdome'), ('06', 'Mão'), ('07', 'Membro superior'), ('08', 'Membro inferior'), ('09', 'Pé'), ('10', 'Todo o corpo'), ('11', 'Outro'), ('99', 'Ignorado')], help_text='Parte do corpo atingida no acidente - 2ª ocorrência.', max_length=2, null=True, verbose_name='Parte do corpo atingida 2')),
                ('tp_parte_corpo_3', models.CharField(blank=True, choices=[('01', 'Olho'), ('02', 'Cabeça'), ('03', 'Pescoço'), ('04', 'Tórax'), ('05', 'Abdome'), ('06', 'Mão'), ('07', 'Membro superior'), ('08', 'Membro inferior'), ('09', 'Pé'), ('10', 'Todo o corpo'), ('11', 'Outro'), ('99', 'Ignorado')], help_text='Parte do corpo atingida no acidente - 3ª ocorrência.', max_length=2, null=True, verbose_name='Parte do corpo atingida 3')),
                ('co_cid_lesao', models.CharField(help_text='Código CID-10 do diagnóstico da lesão.', max_length=4, verbose_name='CID-10 da lesão')),
                ('tp_regime_tratamento', models.CharField(blank=True, choices=[('1', 'Hospitalar'), ('2', 'Ambulatório'), ('3', 'Ambos'), ('9', 'Ignorado')], help_text='Tipo de tratamento recebido.', max_length=1, null=True, verbose_name='Regime de tratamento')),
                ('tp_evolucao_caso', models.CharField(blank=True, choices=[('1', 'Cura'), ('2', 'Incapacidade temporária'), ('3', 'Incapacidade parcial permanente'), ('4', 'Incapacidade total permanente'), ('5', 'Óbito por acidente de trabalho grave'), ('6', 'Óbito por outras causas'), ('7', 'Outro'), ('9', 'Ignorado')], help_text='Evolução do paciente após o acidente.', max_length=1, null=True, verbose_name='Evolução do caso')),
                ('dt_obito', models.DateField(blank=True, help_text='Data do óbito. Deve ser >= data do acidente.', null=True, verbose_name='Data do óbito')),
                ('tp_comunicacao_cat', models.CharField(choices=[('1', 'Sim'), ('2', 'Não'), ('3', 'Não se aplica'), ('9', 'Ignorado')], help_text='Se foi emitida a Comunicação de Acidente no Trabalho (CAT).', max_length=1, verbose_name='Comunicação de Acidente no Trabalho - CAT')),
                ('ds_observacao_acidente', models.CharField(blank=True, help_text='Descrição sumária de como ocorreu o acidente/atividades/causas/condições/objeto/agentes.', max_length=255, null=True, verbose_name='Observações')),
                ('nu_lote_vertical', models.CharField(blank=True, help_text='Identificador do lote de transferência vertical da investigação entre níveis do sistema.', max_length=7, null=True, verbose_name='Lote de transferência vertical')),
            ],
            options={
                'verbose_name': 'Acidente de Trabalho Grave',
                'verbose_name_plural': 'Acidentes de Trabalho Graves',
                'db_table': 'acidente_trabalho_grave',
                'ordering': ['-created_date'],
            },
        ),
    ]
