# Generated by Django 6.0.4 on 2026-04-29 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CancerRelacionadoTrabalho',
            fields=[
                ('id', models.BigAutoField(help_text='Chave primária do registro', primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Código de identificação do registro', max_length=10, verbose_name='Código')),
                ('created_date', models.DateTimeField(auto_now_add=True, help_text='Timestamp de criação do registro', verbose_name='Data de criação')),
                ('created_by', models.CharField(help_text='Usuário que criou o registro', max_length=256, verbose_name='Criado por')),
                ('last_modified_date', models.DateTimeField(auto_now=True, help_text='Timestamp da última modificação do registro', verbose_name='Data de última modificação')),
                ('last_modified_by', models.CharField(help_text='Usuário que realizou a última modificação', max_length=256, verbose_name='Modificado por')),
                ('status', models.CharField(help_text='Status do registro', max_length=20, verbose_name='Status')),
                ('co_cbo_ocupacao', models.CharField(help_text='Ocupação do indivíduo que sofreu o agravo.', max_length=6, verbose_name='Ocupação (CBO)')),
                ('tp_mercado_trabalho', models.CharField(blank=True, choices=[('01', 'Empregado registrado com carteira assinada'), ('02', 'Empregado não registrado'), ('03', 'Autônomo/conta própria'), ('04', 'Servidor público estatutário'), ('05', 'Servidor público celetista'), ('06', 'Aposentado'), ('07', 'Desempregado'), ('08', 'Trabalho temporário'), ('09', 'Cooperativado'), ('10', 'Trabalhador avulso'), ('11', 'Empregador'), ('12', 'Outros'), ('99', 'Ignorado')], help_text='Situação de trabalho do indivíduo que sofreu o agravo.', max_length=2, null=True, verbose_name='Situação no mercado de trabalho')),
                ('nu_tempo_trabalho', models.CharField(blank=True, help_text='Quantidade de tempo trabalhado na ocupação.', max_length=2, null=True, verbose_name='Tempo de trabalho na ocupação')),
                ('tp_tempo_trabalho', models.CharField(blank=True, choices=[('1', 'Hora'), ('2', 'Dias'), ('3', 'Meses'), ('4', 'Anos')], help_text='Unidade de medida do tempo de trabalho.', max_length=1, null=True, verbose_name='Unidade de tempo')),
                ('nu_cnpj_cpf', models.CharField(blank=True, help_text='Número de registro/CNPJ ou CPF do contratante.', max_length=18, null=True, verbose_name='CNPJ/CPF do contratante')),
                ('no_empresa', models.CharField(blank=True, help_text='Nome da empresa ou empregador contratante.', max_length=70, null=True, verbose_name='Nome da empresa ou empregador')),
                ('co_cnae', models.CharField(blank=True, help_text='Classificação Nacional da Atividade Econômica do Contratante.', max_length=10, null=True, verbose_name='CNAE')),
                ('co_uf_empresa', models.CharField(blank=True, help_text='Unidade da Federação da empresa contratante.', max_length=2, null=True, verbose_name='UF da empresa')),
                ('co_municipio_empresa', models.CharField(blank=True, help_text='Município da empresa contratante.', max_length=6, null=True, verbose_name='Município da empresa')),
                ('co_distrito_empresa', models.CharField(blank=True, help_text='Código do distrito da empresa contratante.', max_length=9, null=True, verbose_name='Distrito da empresa')),
                ('no_distrito_empresa', models.CharField(blank=True, help_text='Nome do distrito da empresa contratante.', max_length=70, null=True, verbose_name='Nome do distrito da empresa')),
                ('co_bairro_empresa', models.CharField(blank=True, help_text='Código do bairro da empresa contratante.', max_length=8, null=True, verbose_name='Código do bairro da empresa')),
                ('no_bairro_empresa', models.CharField(blank=True, help_text='Nome do bairro da empresa contratante.', max_length=60, null=True, verbose_name='Bairro da empresa')),
                ('co_endereco_empresa', models.CharField(blank=True, help_text='Código do endereço da empresa contratante.', max_length=60, null=True, verbose_name='Código do endereço da empresa')),
                ('no_endereco_empresa', models.CharField(blank=True, help_text='Endereço da empresa contratante.', max_length=60, null=True, verbose_name='Endereço da empresa')),
                ('nu_numero_empresa', models.CharField(blank=True, help_text='Número do lote da empresa contratante.', max_length=6, null=True, verbose_name='Número do endereço da empresa')),
                ('no_referencia_empresa', models.CharField(blank=True, help_text='Ponto de referência da empresa contratante.', max_length=70, null=True, verbose_name='Ponto de referência da empresa')),
                ('ds_ddd_empresa', models.CharField(blank=True, help_text='DDD e telefone da empresa contratante.', max_length=8, null=True, verbose_name='DDD e Telefone da empresa')),
                ('tp_empresa_terceirizada', models.CharField(blank=True, choices=[('1', 'Sim'), ('2', 'Não'), ('3', 'Não se aplica'), ('9', 'Ignorado')], help_text='O empregador é de alguma empresa terceirizada.', max_length=2, null=True, verbose_name='Empregador é empresa terceirizada')),
                ('nu_tempo_exposicao_risco', models.CharField(blank=True, help_text='Quantidade de tempo de exposição ao agente de risco.', max_length=2, null=True, verbose_name='Tempo de exposição ao agente de risco')),
                ('tp_tempo_exposicao_risco', models.CharField(blank=True, choices=[('1', 'Hora'), ('2', 'Dia'), ('3', 'Meses'), ('4', 'Anos')], help_text='Unidade de medida do tempo de exposição.', max_length=1, null=True, verbose_name='Unidade de tempo de exposição')),
                ('st_regime_tratamento', models.CharField(blank=True, choices=[('1', 'Hospitalar'), ('2', 'Ambulatorial')], help_text='O tratamento ocorreu em regime hospitalar ou ambulatorial.', max_length=1, null=True, verbose_name='Regime de tratamento')),
                ('co_cid_diagnostico', models.CharField(help_text='Código CID-10 do diagnóstico específico.', max_length=4, verbose_name='CID-10 do diagnóstico')),
                ('st_exp_asbesto_amianto', models.CharField(blank=True, choices=[('1', 'Sim'), ('2', 'Não'), ('9', 'Ignorado')], help_text='Exposição a asbesto ou amianto durante a vida profissional.', max_length=1, null=True, verbose_name='Exposição - Asbesto ou Amianto')),
                ('st_exp_cadmio', models.CharField(blank=True, choices=[('1', 'Sim'), ('2', 'Não'), ('9', 'Ignorado')], help_text='Exposição a cádmio ou seus compostos durante a vida profissional.', max_length=1, null=True, verbose_name='Exposição - Cádmio ou seus compostos')),
                ('st_exp_silica', models.CharField(blank=True, choices=[('1', 'Sim'), ('2', 'Não'), ('9', 'Ignorado')], help_text='Exposição a sílica livre, arsênico e seus compostos arsenicais durante a vida profissional.', max_length=1, null=True, verbose_name='Exposição - Sílica livre, arsênico e seus compostos arsenicais')),
                ('st_exp_cromo', models.CharField(blank=True, choices=[('1', 'Sim'), ('2', 'Não'), ('9', 'Ignorado')], help_text='Exposição a cromo ou seus compostos tóxicos durante a vida profissional.', max_length=1, null=True, verbose_name='Exposição - Cromo ou seus compostos tóxicos')),
                ('st_exp_amina_aromatica', models.CharField(blank=True, choices=[('1', 'Sim'), ('2', 'Não'), ('9', 'Ignorado')], help_text='Exposição a aminas aromáticas durante a vida profissional.', max_length=1, null=True, verbose_name='Exposição - Aminas Aromáticas')),
                ('st_exp_composto_niquel', models.CharField(blank=True, choices=[('1', 'Sim'), ('2', 'Não'), ('9', 'Ignorado')], help_text='Exposição a compostos de níquel durante a vida profissional.', max_length=1, null=True, verbose_name='Exposição - Composto de Níquel')),
                ('st_exp_benzeno', models.CharField(blank=True, choices=[('1', 'Sim'), ('2', 'Não'), ('9', 'Ignorado')], help_text='Exposição a benzeno ou seus homólogos tóxicos durante a vida profissional.', max_length=1, null=True, verbose_name='Exposição - Benzeno ou seus homólogos tóxicos')),
                ('st_exp_radiacao_ionizante', models.CharField(blank=True, choices=[('1', 'Sim'), ('2', 'Não'), ('9', 'Ignorado')], help_text='Exposição a radiações ionizantes durante a vida profissional.', max_length=1, null=True, verbose_name='Exposição - Radiações Ionizantes')),
                ('st_exp_alcatrao', models.CharField(blank=True, choices=[('1', 'Sim'), ('2', 'Não'), ('9', 'Ignorado')], help_text='Exposição a alcatrão, breu, betume, hulha mineral, parafina e produtos ou resíduos dessas substâncias durante a vida profissional.', max_length=1, null=True, verbose_name='Exposição - Alcatrão, breu, betume, hulha mineral, parafina')),
                ('st_exp_radiacao_nao_ionizante', models.CharField(blank=True, choices=[('1', 'Sim'), ('2', 'Não'), ('9', 'Ignorado')], help_text='Exposição a radiações não ionizantes durante a vida profissional.', max_length=1, null=True, verbose_name='Exposição - Radiações não Ionizantes')),
                ('st_exp_hidrocarboneto', models.CharField(blank=True, choices=[('1', 'Sim'), ('2', 'Não'), ('9', 'Ignorado')], help_text='Exposição a hidrocarbonetos alifáticos ou aromáticos (seus derivados halogenados) durante a vida profissional.', max_length=1, null=True, verbose_name='Exposição - Hidrocarbonetos alifáticos ou aromáticos')),
                ('st_exp_hormonio', models.CharField(blank=True, choices=[('1', 'Sim'), ('2', 'Não'), ('9', 'Ignorado')], help_text='Exposição a hormônios durante a vida profissional.', max_length=1, null=True, verbose_name='Exposição - Hormônios')),
                ('st_exp_oleo_mineral', models.CharField(blank=True, choices=[('1', 'Sim'), ('2', 'Não'), ('9', 'Ignorado')], help_text='Exposição a óleos minerais durante a vida profissional.', max_length=1, null=True, verbose_name='Exposição - Óleos Minerais')),
                ('st_exp_antineoplasico', models.CharField(blank=True, choices=[('1', 'Sim'), ('2', 'Não'), ('9', 'Ignorado')], help_text='Exposição a antineoplásicos durante a vida profissional.', max_length=1, null=True, verbose_name='Exposição - Antineoplásicos')),
                ('st_exp_berilio', models.CharField(blank=True, choices=[('1', 'Sim'), ('2', 'Não'), ('9', 'Ignorado')], help_text='Exposição a berílio e seus compostos tóxicos durante a vida profissional.', max_length=1, null=True, verbose_name='Exposição - Berílio e seus compostos tóxicos')),
                ('st_exp_outro', models.CharField(blank=True, choices=[('1', 'Sim'), ('2', 'Não'), ('9', 'Ignorado')], help_text='Exposição a outros agentes de risco durante a vida profissional.', max_length=1, null=True, verbose_name='Exposição - Outros agentes')),
                ('ds_exp_outro', models.CharField(blank=True, help_text='Especificação de outros agentes de risco.', max_length=30, null=True, verbose_name='Outros agentes (especificar)')),
                ('tp_habito_fumar', models.CharField(blank=True, choices=[('1', 'Sim'), ('2', 'Não'), ('3', 'Ex-fumante'), ('9', 'Ignorado')], help_text='Hábito de fumar do paciente.', max_length=1, null=True, verbose_name='Hábito de fumar')),
                ('nu_tempo_exposicao_tabaco', models.CharField(blank=True, help_text='Quantidade de tempo de exposição ao tabaco.', max_length=2, null=True, verbose_name='Tempo de exposição ao tabaco')),
                ('tp_tempo_exposicao_tabaco', models.CharField(blank=True, choices=[('1', 'Hora'), ('2', 'Dia'), ('3', 'Meses'), ('4', 'Anos')], help_text='Unidade de medida do tempo de exposição ao tabaco.', max_length=1, null=True, verbose_name='Unidade de tempo - Exposição ao tabaco')),
                ('st_trabalhador_mesma_doenca', models.CharField(blank=True, choices=[('1', 'Sim'), ('2', 'Não'), ('9', 'Ignorado')], help_text='Se há ou houve outros trabalhadores com a mesma doença no local de trabalho.', max_length=1, null=True, verbose_name='Outros trabalhadores com a mesma doença')),
                ('tp_evolucao_caso', models.CharField(blank=True, choices=[('1', 'Sem evidência da doença (remissão completa)'), ('2', 'Remissão parcial'), ('3', 'Doença estável'), ('4', 'Doença em Progressão'), ('5', 'Fora de possibilidade terapêutica'), ('6', 'Óbito por câncer relacionado ao trabalho'), ('7', 'Óbito por outras causas'), ('8', 'Não se aplica'), ('9', 'Ignorado')], help_text='Evolução da situação do paciente.', max_length=1, null=True, verbose_name='Evolução do caso')),
                ('dt_obito', models.DateField(blank=True, help_text='Data do óbito. Obrigatório se evolução = 6 ou 7. Deve ser >= data do diagnóstico.', null=True, verbose_name='Data do óbito')),
                ('tp_comunicacao_cat', models.CharField(choices=[('1', 'Sim'), ('2', 'Não'), ('3', 'Não se aplica'), ('9', 'Ignorado')], help_text='Se foi emitida a comunicação de Acidente de Trabalho (CAT).', max_length=1, verbose_name='Comunicação de Acidente de Trabalho - CAT')),
                ('ds_observacao', models.CharField(blank=True, help_text='Informações complementares e observações a respeito do caso quando necessário.', max_length=255, null=True, verbose_name='Observações')),
                ('nu_lote_vertical', models.CharField(blank=True, help_text='Identificador do lote de transferência vertical da investigação entre níveis do sistema.', max_length=7, null=True, verbose_name='Lote de transferência vertical')),
            ],
            options={
                'verbose_name': 'Câncer Relacionado ao Trabalho',
                'verbose_name_plural': 'Câncer Relacionado ao Trabalho',
                'db_table': 'cancer_relacionado_trabalho',
                'ordering': ['-created_date'],
            },
        ),
    ]
