# Generated by Django 6.0.4 on 2026-04-29 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GestanteHiv',
            fields=[
                ('id', models.BigAutoField(help_text='Chave primária do registro', primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Código de identificação do registro', max_length=10, verbose_name='Código')),
                ('created_date', models.DateTimeField(auto_now_add=True, help_text='Timestamp de criação do registro', verbose_name='Data de criação')),
                ('created_by', models.CharField(help_text='Usuário que criou o registro', max_length=256, verbose_name='Criado por')),
                ('last_modified_date', models.DateTimeField(auto_now=True, help_text='Timestamp da última modificação do registro', verbose_name='Data de última modificação')),
                ('last_modified_by', models.CharField(help_text='Usuário que realizou a última modificação', max_length=256, verbose_name='Modificado por')),
                ('status', models.CharField(help_text='Status do registro', max_length=20, verbose_name='Status')),
                ('co_cbo_ocupacao', models.CharField(blank=True, help_text='Código CBO da ocupação exercida pela gestante.', max_length=6, null=True, verbose_name='Ocupação (CBO)')),
                ('tp_evidencia_laboratorial', models.CharField(choices=[('1', 'Antes do pré-natal'), ('2', 'Durante o pré-natal'), ('3', 'Durante o parto'), ('4', 'Após o parto')], help_text='Momento em que foi realizada a coleta do material no qual se evidenciou o diagnóstico laboratorial da infecção pelo HIV na gestante/parturiente.', max_length=1, verbose_name='Evidência laboratorial do HIV')),
                ('st_fez_prenatal', models.CharField(blank=True, choices=[('1', 'Sim'), ('2', 'Não'), ('9', 'Ignorado')], help_text='Registra se a gestante HIV+ ou com diagnóstico confirmado de aids fez ou faz pré-natal.', max_length=1, null=True, verbose_name='Fez/faz pré-natal')),
                ('co_uf_prenatal', models.CharField(blank=True, help_text='Sigla da UF de localização da Unidade de Saúde de realização do pré-natal.', max_length=2, null=True, verbose_name='UF de realização do pré-natal')),
                ('co_municipio_prenatal', models.CharField(blank=True, help_text='Código do município de localização da Unidade de Saúde de realização do pré-natal.', max_length=6, null=True, verbose_name='Município de realização do pré-natal')),
                ('co_unidade_prenatal', models.CharField(blank=True, help_text='Código CNES da unidade de saúde de realização do pré-natal.', max_length=7, null=True, verbose_name='Unidade de realização do pré-natal')),
                ('nu_sisprenatal', models.DecimalField(blank=True, decimal_places=0, help_text='Número identificador da gestante no cadastro do SISPRENATAL.', max_digits=10, null=True, verbose_name='Nº da gestante no SISPRENATAL')),
                ('st_anti_retroviral', models.CharField(blank=True, choices=[('1', 'Sim'), ('2', 'Não'), ('9', 'Ignorado')], help_text='Gestante HIV+ em terapia com anti-retrovirais para profilaxia.', max_length=1, null=True, verbose_name='Uso de anti-retrovirais para profilaxia')),
                ('dt_ini_anti_retroviral', models.DateField(blank=True, help_text='Data de início de uso de anti-retroviral para profilaxia.', null=True, verbose_name='Data do início do uso de anti-retroviral')),
                ('co_uf_parto', models.CharField(blank=True, help_text='UF de localização da ocorrência do parto.', max_length=2, null=True, verbose_name='UF do local do parto')),
                ('co_municipio_parto', models.CharField(blank=True, help_text='Código do município de localização da ocorrência do parto.', max_length=6, null=True, verbose_name='Município do local do parto')),
                ('co_unidade_parto', models.CharField(blank=True, help_text='Código CNES da unidade de saúde onde ocorreu o parto.', max_length=7, null=True, verbose_name='Local de realização do parto')),
                ('dt_parto', models.DateField(blank=True, help_text='Data em que ocorreu o parto.', null=True, verbose_name='Data do parto')),
                ('tp_parto', models.CharField(blank=True, choices=[('1', 'Vaginal'), ('2', 'Cesárea eletiva'), ('3', 'Cesárea de urgência'), ('4', 'Não se aplica')], help_text='Tipo de parto realizado.', max_length=1, null=True, verbose_name='Tipo do parto')),
                ('st_uso_anti_retroviral_parto', models.CharField(blank=True, choices=[('1', 'Sim'), ('2', 'Não'), ('9', 'Ignorado')], help_text='Anti-retrovirais administrados durante o parto.', max_length=1, null=True, verbose_name='Uso de profilaxia anti-retroviral durante o parto')),
                ('tp_evolucao_gravidez', models.CharField(blank=True, choices=[('1', 'Nascido vivo'), ('2', 'Natimorto'), ('3', 'Aborto'), ('4', 'Não se aplica')], help_text='Evolução da gravidez.', max_length=1, null=True, verbose_name='Evolução da gravidez')),
                ('tp_profilaxia_anti_retroviral', models.CharField(blank=True, choices=[('1', 'Nas primeiras 24h'), ('2', 'Após 24h do nascimento'), ('3', 'Não se aplica'), ('4', 'Não realizado'), ('9', 'Ignorado')], help_text='Início da administração do anti-retroviral, em número de horas, a partir do nascimento.', max_length=1, null=True, verbose_name='Início da profilaxia com anti-retroviral na criança')),
                ('ds_observacao', models.CharField(blank=True, help_text='Informações complementares e observações a respeito do caso.', max_length=255, null=True, verbose_name='Observações')),
                ('nu_lote_vertical', models.CharField(blank=True, help_text='Identificador do lote de transferência vertical da investigação entre níveis do sistema.', max_length=7, null=True, verbose_name='Lote de transferência vertical')),
            ],
            options={
                'verbose_name': 'Gestante HIV',
                'verbose_name_plural': 'Gestantes HIV',
                'db_table': 'gestante_hiv',
                'ordering': ['-created_date'],
            },
        ),
    ]
