# Generated by Django 6.0.4 on 2026-04-28 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coqueluche',
            fields=[
                ('id', models.BigAutoField(help_text='Chave primária do registro', primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Código de identificação do registro', max_length=10, verbose_name='Código')),
                ('created_date', models.DateTimeField(auto_now_add=True, help_text='Timestamp de criação do registro', verbose_name='Data de criação')),
                ('created_by', models.CharField(help_text='Usuário que criou o registro', max_length=256, verbose_name='Criado por')),
                ('last_modified_date', models.DateTimeField(auto_now=True, help_text='Timestamp da última modificação do registro', verbose_name='Data de última modificação')),
                ('last_modified_by', models.CharField(help_text='Usuário que realizou a última modificação', max_length=256, verbose_name='Modificado por')),
                ('status', models.CharField(help_text='Status do registro', max_length=20, verbose_name='Status')),
                ('dt_investigacao', models.DateField(help_text='Data completa do início da investigação. Deve ser >= data da notificação e <= data atual.', verbose_name='Data da investigação')),
                ('co_cbo_ocupacao', models.CharField(blank=True, help_text='Código CBO da ocupação exercida pelo paciente.', max_length=6, null=True, verbose_name='Ocupação (CBO)')),
                ('st_unidade_sentinela', models.CharField(choices=[('1', 'Sim'), ('2', 'Não'), ('9', 'Ignorado')], help_text='Informa se a unidade de saúde que notificou o caso é considerada sentinela.', max_length=1, verbose_name='Unidade notificante é sentinela')),
                ('tp_contato_coqueluche', models.CharField(blank=True, choices=[('1', 'Domicílio'), ('2', 'Vizinhança'), ('3', 'Trabalho'), ('4', 'Creche/escola'), ('5', 'Posto de saúde/hospital'), ('6', 'Outro Estado/Município'), ('7', 'Outro'), ('8', 'Sem história de contato'), ('9', 'Ignorado')], help_text='Local em que o paciente teve contato com caso semelhante nos últimos 14 dias.', max_length=1, null=True, verbose_name='Contato com caso suspeito ou confirmado')),
                ('ds_contato_coqueluche_outro', models.CharField(blank=True, help_text='Especificação quando contato = 7 (Outro).', max_length=30, null=True, verbose_name='Outro contato (especificar)')),
                ('no_contato', models.CharField(blank=True, help_text='Nome completo do contato.', max_length=70, null=True, verbose_name='Nome do contato')),
                ('co_endereco_contato', models.CharField(blank=True, help_text='Código do endereço completo do contato.', max_length=60, null=True, verbose_name='Código do endereço do contato')),
                ('no_endereco_contato', models.CharField(blank=True, help_text='Endereço completo do contato.', max_length=60, null=True, verbose_name='Endereço do contato')),
                ('tp_dose_vacina', models.CharField(blank=True, choices=[('1', 'Uma'), ('2', 'Duas'), ('3', 'Três'), ('4', 'Três + 1 Reforço'), ('5', 'Três + 2 Reforços'), ('6', 'Nunca Vacinado'), ('9', 'Ignorado')], help_text='Número de doses da vacina tríplice (DPT) ou tetravalente (DTP+Hib) recebidas.', max_length=1, null=True, verbose_name='Nº de doses da vacina')),
                ('dt_ultima_dose', models.DateField(blank=True, help_text='Data da última dose da vacina tríplice (DTP) recebida. Deve ser > data de nascimento e <= data atual.', null=True, verbose_name='Data da última dose')),
                ('dt_inicio_tosse', models.DateField(help_text='Data do início da tosse. Deve ser inferior a 14 dias antes da data de notificação.', verbose_name='Data do início da tosse')),
                ('st_sinais_tosse', models.CharField(choices=[('1', 'Sim'), ('2', 'Não'), ('9', 'Ignorado')], help_text='Informa se o paciente apresentou tosse.', max_length=1, verbose_name='Tosse')),
                ('st_sinais_tosse_paroxistica', models.CharField(choices=[('1', 'Sim'), ('2', 'Não'), ('9', 'Ignorado')], help_text='Informa se o paciente apresentou tosse paroxística (tosse súbita incontrolável com tossidas rápidas e curtas).', max_length=1, verbose_name='Tosse paroxística')),
                ('st_sinais_respiracao', models.CharField(choices=[('1', 'Sim'), ('2', 'Não'), ('9', 'Ignorado')], help_text='Informa se o paciente apresentou respiração ruidosa ao final da crise de tosse (guincho).', max_length=1, verbose_name='Respiração ruidosa (guincho)')),
                ('st_sinais_cianose', models.CharField(blank=True, choices=[('1', 'Sim'), ('2', 'Não'), ('9', 'Ignorado')], help_text='Informa se o paciente apresentou cianose.', max_length=1, null=True, verbose_name='Cianose')),
                ('st_sinais_vomito', models.CharField(choices=[('1', 'Sim'), ('2', 'Não'), ('9', 'Ignorado')], help_text='Informa se o paciente apresentou vômitos pós-tosse.', max_length=1, verbose_name='Vômitos pós-tosse')),
                ('st_sinais_apneia', models.CharField(blank=True, choices=[('1', 'Sim'), ('2', 'Não'), ('9', 'Ignorado')], help_text='Informa se o paciente apresentou apnéia.', max_length=1, null=True, verbose_name='Apnéia')),
                ('st_sinais_temperatura_menor_38', models.CharField(blank=True, choices=[('1', 'Sim'), ('2', 'Não'), ('9', 'Ignorado')], help_text='Informa se o paciente apresentou temperatura < 38°C.', max_length=1, null=True, verbose_name='Temperatura < 38°C')),
                ('st_sinais_temperatura_maior_38', models.CharField(blank=True, choices=[('1', 'Sim'), ('2', 'Não'), ('9', 'Ignorado')], help_text='Informa se o paciente apresentou temperatura >= 38°C.', max_length=1, null=True, verbose_name='Temperatura >= 38°C')),
                ('st_sinais_outro', models.CharField(blank=True, choices=[('1', 'Sim'), ('2', 'Não'), ('9', 'Ignorado')], help_text='Informa se o paciente apresentou outros sintomas.', max_length=1, null=True, verbose_name='Outros sinais/sintomas')),
                ('ds_sinais_outro', models.CharField(blank=True, help_text='Especificação de outros sinais e sintomas.', max_length=30, null=True, verbose_name='Outros sinais/sintomas (especificar)')),
                ('st_complicacao_pneumonia', models.CharField(blank=True, choices=[('1', 'Sim'), ('2', 'Não'), ('9', 'Ignorado')], help_text='Informa se o paciente apresentou pneumonia ou broncopneumonia.', max_length=1, null=True, verbose_name='Pneumonia ou broncopneumonia')),
                ('st_complicacao_encefalopatia', models.CharField(blank=True, choices=[('1', 'Sim'), ('2', 'Não'), ('9', 'Ignorado')], help_text='Informa se o paciente apresentou encefalopatia (convulsões).', max_length=1, null=True, verbose_name='Encefalopatia (convulsões)')),
                ('st_complicacao_desidratacao', models.CharField(blank=True, choices=[('1', 'Sim'), ('2', 'Não'), ('9', 'Ignorado')], help_text='Informa se o paciente apresentou desidratação.', max_length=1, null=True, verbose_name='Desidratação')),
                ('st_complicacao_otite', models.CharField(blank=True, choices=[('1', 'Sim'), ('2', 'Não'), ('9', 'Ignorado')], help_text='Informa se o paciente apresentou otite.', max_length=1, null=True, verbose_name='Otite')),
                ('st_complicacao_desnutricao', models.CharField(blank=True, choices=[('1', 'Sim'), ('2', 'Não'), ('9', 'Ignorado')], help_text='Informa se o paciente apresentou desnutrição.', max_length=1, null=True, verbose_name='Desnutrição')),
                ('st_complicacao_outro', models.CharField(blank=True, choices=[('1', 'Sim'), ('2', 'Não'), ('9', 'Ignorado')], help_text='Informa se o paciente apresentou outras complicações.', max_length=1, null=True, verbose_name='Outras complicações')),
                ('ds_complicacao_outro', models.CharField(blank=True, help_text='Especificação de outras complicações.', max_length=30, null=True, verbose_name='Outras complicações (especificar)')),
                ('st_ocorreu_hospitalizacao', models.CharField(blank=True, choices=[('1', 'Sim'), ('2', 'Não'), ('9', 'Ignorado')], help_text='Informa se o paciente foi hospitalizado.', max_length=1, null=True, verbose_name='Ocorreu hospitalização')),
                ('dt_internacao', models.DateField(blank=True, help_text='Data de internação. Obrigatório se hospitalização = Sim.', null=True, verbose_name='Data da internação')),
                ('co_uf_hospital', models.CharField(blank=True, help_text='Sigla da UF onde o paciente foi internado.', max_length=2, null=True, verbose_name='UF do hospital')),
                ('co_municipio_hospital', models.CharField(blank=True, help_text='Código do município onde está localizado o hospital.', max_length=6, null=True, verbose_name='Município do hospital')),
                ('co_unidade_hospital', models.DecimalField(blank=True, decimal_places=0, help_text='Código do hospital onde o paciente foi internado (CNES).', max_digits=8, null=True, verbose_name='Código do hospital (CNES)')),
                ('st_utilizou_antibiotico', models.CharField(blank=True, choices=[('1', 'Sim'), ('2', 'Não'), ('9', 'Ignorado')], help_text='Informa se o paciente fez uso de antibióticos/antimicrobianos no tratamento.', max_length=1, null=True, verbose_name='Utilizou antibiótico')),
                ('dt_antibiotico', models.DateField(blank=True, help_text='Data da administração do antibiótico. Obrigatório se utilizou antibiótico = Sim.', null=True, verbose_name='Data da administração do antibiótico')),
                ('st_coleta_material', models.CharField(blank=True, choices=[('1', 'Sim'), ('2', 'Não'), ('9', 'Ignorado')], help_text='Informa se foi realizada coleta de material da nasofaringe.', max_length=1, null=True, verbose_name='Coleta de material da nasofaringe')),
                ('dt_coleta', models.DateField(blank=True, help_text='Data da coleta do material da nasofaringe. Obrigatório se coleta = Sim.', null=True, verbose_name='Data da coleta do material')),
                ('tp_resultado_cultura', models.CharField(blank=True, choices=[('1', 'Positiva'), ('2', 'Negativa'), ('3', 'Não realizada'), ('9', 'Ignorado')], help_text='Resultado da cultura do material da nasofaringe (Bordetella pertussis).', max_length=1, null=True, verbose_name='Resultado da cultura')),
                ('st_identificacao_comunicante', models.CharField(blank=True, choices=[('1', 'Sim'), ('2', 'Não'), ('9', 'Ignorado')], help_text='Informa se foram identificados comunicantes íntimos.', max_length=1, null=True, verbose_name='Identificação dos comunicantes íntimos')),
                ('qt_identificacao', models.SmallIntegerField(blank=True, help_text='Número de comunicantes íntimos identificados.', null=True, verbose_name='Quantidade de comunicantes íntimos')),
                ('tp_caso_confirmado', models.CharField(blank=True, choices=[('0', 'Nenhum'), ('1', 'Um'), ('2', 'Dois ou mais'), ('9', 'Ignorado')], help_text='Número de casos secundários identificados entre os comunicantes.', max_length=1, null=True, verbose_name='Casos secundários confirmados')),
                ('st_coleta_material_comunicante', models.CharField(blank=True, choices=[('1', 'Sim'), ('2', 'Não'), ('9', 'Ignorado')], help_text='Informa se foi realizada coleta de material da nasofaringe dos comunicantes.', max_length=1, null=True, verbose_name='Coleta de material dos comunicantes')),
                ('qt_comunicante', models.SmallIntegerField(blank=True, help_text='Número de comunicantes em que foi coletado o material.', null=True, verbose_name='Quantidade de comunicantes com coleta')),
                ('nu_comunicante_positivo', models.SmallIntegerField(blank=True, help_text='Número de comunicantes com resultado da cultura positivo.', null=True, verbose_name='Comunicantes com cultura positiva')),
                ('tp_medida_controle', models.CharField(blank=True, choices=[('1', 'Bloqueio vacinal'), ('2', 'Quimioprofilaxia'), ('3', 'Ambos'), ('4', 'Não'), ('9', 'Ignorado')], help_text='Informa se foi realizado bloqueio e qual tipo.', max_length=1, null=True, verbose_name='Medidas de prevenção/controle')),
                ('tp_classificacao_final', models.CharField(blank=True, choices=[('1', 'Confirmado'), ('2', 'Descartado')], help_text='Classificação final do caso.', max_length=1, null=True, verbose_name='Classificação final')),
                ('tp_criterio_confirmacao', models.CharField(blank=True, choices=[('1', 'Laboratorial'), ('2', 'Vínculo Epidemiológico'), ('3', 'Clínico')], help_text='Critério utilizado para confirmação do caso ou descarte do suspeito.', max_length=1, null=True, verbose_name='Critério de confirmação/descarte')),
                ('st_doenca_trabalho', models.CharField(blank=True, choices=[('1', 'Sim'), ('2', 'Não'), ('9', 'Ignorado')], help_text='Se a doença adquirida está relacionada às condições/situação de trabalho.', max_length=1, null=True, verbose_name='Doença relacionada ao trabalho')),
                ('tp_evolucao_caso', models.CharField(blank=True, choices=[('1', 'Cura'), ('2', 'Óbito por coqueluche'), ('3', 'Óbito por outras causas'), ('9', 'Ignorado')], help_text='Evolução do caso.', max_length=1, null=True, verbose_name='Evolução do caso')),
                ('dt_obito', models.DateField(blank=True, help_text='Data do óbito. Obrigatório se evolução = 2 ou 3.', null=True, verbose_name='Data do óbito')),
                ('dt_encerramento', models.DateField(blank=True, help_text='Data do encerramento do caso. Obrigatório se classificação final preenchida.', null=True, verbose_name='Data do encerramento')),
                ('nu_lote_vertical', models.CharField(blank=True, help_text='Identificador do lote de transferência vertical da investigação entre níveis do sistema.', max_length=7, null=True, verbose_name='Lote de transferência vertical')),
            ],
            options={
                'verbose_name': 'Coqueluche',
                'verbose_name_plural': 'Coqueluche',
                'db_table': 'coqueluche',
                'ordering': ['-created_date'],
            },
        ),
    ]
