# Generated by Django 6.0.4 on 2026-04-28 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AtendimentoAntirabico',
            fields=[
                ('id', models.BigAutoField(help_text='Chave primária do registro', primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Código de identificação do registro', max_length=10, verbose_name='Código')),
                ('created_date', models.DateTimeField(auto_now_add=True, help_text='Timestamp de criação do registro', verbose_name='Data de criação')),
                ('created_by', models.CharField(help_text='Usuário que criou o registro', max_length=256, verbose_name='Criado por')),
                ('last_modified_date', models.DateTimeField(auto_now=True, help_text='Timestamp da última modificação do registro', verbose_name='Data de última modificação')),
                ('last_modified_by', models.CharField(help_text='Usuário que realizou a última modificação', max_length=256, verbose_name='Modificado por')),
                ('status', models.CharField(help_text='Status do registro', max_length=20, verbose_name='Status')),
                ('co_cbo_ocupacao', models.CharField(blank=True, help_text='Código CBO da ocupação exercida pelo paciente.', max_length=6, null=True, verbose_name='Ocupação (CBO)')),
                ('st_exp_virusrabico_indireto', models.CharField(choices=[('1', 'Sim'), ('2', 'Não'), ('9', 'Ignorado')], help_text='Informa se a exposição foi por contato indireto.', max_length=1, verbose_name='Tipo de exposição - Contato Indireto')),
                ('st_exp_virusrabico_arranhadura', models.CharField(choices=[('1', 'Sim'), ('2', 'Não'), ('9', 'Ignorado')], help_text='Informa se a exposição foi por arranhadura.', max_length=1, verbose_name='Tipo de exposição - Arranhadura')),
                ('st_exp_virusrabico_lambedura', models.CharField(choices=[('1', 'Sim'), ('2', 'Não'), ('9', 'Ignorado')], help_text='Informa se a exposição foi por lambedura.', max_length=1, verbose_name='Tipo de exposição - Lambedura')),
                ('st_exp_virusrabico_mordedura', models.CharField(choices=[('1', 'Sim'), ('2', 'Não'), ('9', 'Ignorado')], help_text='Informa se a exposição foi por mordedura.', max_length=1, verbose_name='Tipo de exposição - Mordedura')),
                ('st_exp_virusrabico_outro', models.CharField(choices=[('1', 'Sim'), ('2', 'Não'), ('9', 'Ignorado')], help_text='Informa se houve outro modo de exposição ao vírus rábico.', max_length=1, verbose_name='Tipo de exposição - Outros')),
                ('ds_exp_virusrabico_outro', models.CharField(blank=True, help_text='Especificação de outro modo de exposição ao vírus rábico.', max_length=30, null=True, verbose_name='Tipo de exposição - Outros (especificar)')),
                ('tp_localizacao_mucosa', models.CharField(choices=[('1', 'Sim'), ('2', 'Não'), ('3', 'Desconhecida')], help_text='Informa se o ferimento foi em mucosa.', max_length=1, verbose_name='Localização - Mucosa')),
                ('tp_localizacao_cabeca_pescoco', models.CharField(choices=[('1', 'Sim'), ('2', 'Não'), ('3', 'Desconhecida')], help_text='Informa se o ferimento foi em cabeça ou pescoço.', max_length=1, verbose_name='Localização - Cabeça/Pescoço')),
                ('tp_localizacao_maos_pes', models.CharField(choices=[('1', 'Sim'), ('2', 'Não'), ('3', 'Desconhecida')], help_text='Informa se o ferimento foi em mãos ou pés.', max_length=1, verbose_name='Localização - Mãos/Pés')),
                ('tp_localizacao_tronco', models.CharField(choices=[('1', 'Sim'), ('2', 'Não'), ('3', 'Desconhecida')], help_text='Informa se o ferimento foi em tronco.', max_length=1, verbose_name='Localização - Tronco')),
                ('tp_localizacao_membro_superior', models.CharField(choices=[('1', 'Sim'), ('2', 'Não'), ('3', 'Desconhecida')], help_text='Informa se o ferimento foi em membros superiores.', max_length=1, verbose_name='Localização - Membros Superiores')),
                ('tp_localizacao_membro_inferior', models.CharField(choices=[('1', 'Sim'), ('2', 'Não'), ('3', 'Desconhecida')], help_text='Informa se o ferimento foi em membros inferiores.', max_length=1, verbose_name='Localização - Membros Inferiores')),
                ('tp_ferimento', models.CharField(choices=[('1', 'Único'), ('2', 'Múltiplo'), ('3', 'Sem ferimento'), ('9', 'Ignorado')], help_text='Informa se o ferimento é único, múltiplo, inexistente ou ignorado.', max_length=1, verbose_name='Ferimento')),
                ('st_tipo_ferimento_profundo', models.CharField(blank=True, choices=[('1', 'Sim'), ('2', 'Não'), ('9', 'Ignorado')], help_text='Informa se o ferimento é profundo.', max_length=1, null=True, verbose_name='Tipo de ferimento - Profundo')),
                ('st_tipo_ferimento_superficial', models.CharField(blank=True, choices=[('1', 'Sim'), ('2', 'Não'), ('9', 'Ignorado')], help_text='Informa se o ferimento é superficial.', max_length=1, null=True, verbose_name='Tipo de ferimento - Superficial')),
                ('st_tipo_ferimento_desconhecido', models.CharField(blank=True, choices=[('1', 'Sim'), ('2', 'Não'), ('9', 'Ignorado')], help_text='Informa se o tipo de ferimento é desconhecido.', max_length=1, null=True, verbose_name='Tipo de ferimento - Desconhecido')),
                ('dt_exposicao', models.DateField(help_text='Data da ocorrência da agressão. Deve ser <= data de atendimento.', verbose_name='Data da exposição')),
                ('st_ante_trat_antirabico_pre_exp', models.CharField(blank=True, choices=[('1', 'Sim'), ('2', 'Não'), ('9', 'Ignorado')], help_text='Informa se houve tratamento anti-rábico pré-exposição.', max_length=1, null=True, verbose_name='Antecedente - Pré-exposição')),
                ('st_ante_trat_antirabico_pos_exp', models.CharField(blank=True, choices=[('1', 'Sim'), ('2', 'Não'), ('9', 'Ignorado')], help_text='Informa se houve tratamento anti-rábico pós-exposição completo.', max_length=1, null=True, verbose_name='Antecedente - Pós-exposição completo')),
                ('st_concluido', models.CharField(blank=True, choices=[('1', 'Até 90 dias'), ('2', 'Após 90 dias')], help_text='Período de conclusão do tratamento antecedente.', max_length=1, null=True, verbose_name='Quando foi concluído')),
                ('nu_dose_aplicada', models.SmallIntegerField(blank=True, help_text='Número de doses aplicadas no tratamento antecedente.', null=True, verbose_name='Número de doses aplicadas')),
                ('tp_animal_agressor', models.CharField(choices=[('1', 'Canina'), ('2', 'Felina'), ('3', 'Quiróptera (morcego)'), ('4', 'Primata (macaco)'), ('5', 'Raposa'), ('6', 'Herbívoro doméstico'), ('7', 'Outra')], help_text='Espécie do animal responsável pela agressão.', max_length=1, verbose_name='Espécie do animal agressor')),
                ('ds_animal_agressor_herbivoro', models.CharField(blank=True, help_text='Especificar o herbívoro doméstico agressor.', max_length=30, null=True, verbose_name='Herbívoro doméstico (especificar)')),
                ('ds_animal_agressor_outro', models.CharField(blank=True, help_text='Especificar outra espécie de animal agressor.', max_length=30, null=True, verbose_name='Outra espécie (especificar)')),
                ('tp_condicao_animal_tratamento', models.CharField(blank=True, choices=[('1', 'Sadio'), ('2', 'Suspeito'), ('3', 'Raivoso'), ('4', 'Morto/desaparecido')], help_text='Condição do animal após a agressão para fins de conduta do tratamento.', max_length=1, null=True, verbose_name='Condição do animal')),
                ('tp_animal_passivel_obs', models.CharField(blank=True, choices=[('1', 'Sim'), ('2', 'Não')], help_text='Informa se o animal pode ser observado (somente para cão ou gato).', max_length=1, null=True, verbose_name='Animal passível de observação')),
                ('tp_tratamento_indicado', models.CharField(blank=True, choices=[('1', 'Pré-exposição'), ('2', 'Dispensa de tratamento'), ('3', 'Observação do animal (se cão ou gato)'), ('4', 'Observação + vacina'), ('5', 'Vacina'), ('6', 'Soro + vacina'), ('7', 'Esquema de Reexposição')], help_text='Tipo de tratamento atualmente indicado.', max_length=1, null=True, verbose_name='Tratamento indicado')),
                ('tp_produtor_vacina', models.CharField(blank=True, choices=[('1', 'Instituto Butantan'), ('2', 'Instituto Vital Brasil'), ('3', 'Aventis Pasteur'), ('4', 'Outro')], help_text='Laboratório produtor da vacina utilizada.', max_length=1, null=True, verbose_name='Laboratório produtor da vacina')),
                ('ds_produtor_vacina_outro', models.CharField(blank=True, help_text='Especificar outro laboratório produtor da vacina.', max_length=30, null=True, verbose_name='Outro produtor de vacina (especificar)')),
                ('nu_lote', models.CharField(blank=True, help_text='Número do lote da primeira vacina.', max_length=10, null=True, verbose_name='Número do lote')),
                ('dt_vencimento', models.DateField(blank=True, help_text='Data do vencimento da primeira vacina.', null=True, verbose_name='Data do vencimento')),
                ('dt_vacina_dose_1', models.DateField(blank=True, help_text='Data da aplicação da primeira dose.', null=True, verbose_name='Data da 1ª dose da vacina')),
                ('dt_vacina_dose_2', models.DateField(blank=True, help_text='Data da aplicação da segunda dose.', null=True, verbose_name='Data da 2ª dose da vacina')),
                ('dt_vacina_dose_3', models.DateField(blank=True, help_text='Data da aplicação da terceira dose.', null=True, verbose_name='Data da 3ª dose da vacina')),
                ('dt_vacina_dose_4', models.DateField(blank=True, help_text='Data da aplicação da quarta dose.', null=True, verbose_name='Data da 4ª dose da vacina')),
                ('dt_vacina_dose_5', models.DateField(blank=True, help_text='Data da aplicação da quinta dose.', null=True, verbose_name='Data da 5ª dose da vacina')),
                ('tp_condicao_animal', models.CharField(blank=True, choices=[('1', 'Negativo para raiva (clínica)'), ('2', 'Negativo para raiva (laboratório)'), ('3', 'Positivo para raiva (clínica)'), ('4', 'Positivo para raiva (laboratório)'), ('5', 'Morto/sacrificado/sem diagnóstico'), ('9', 'Ignorado')], help_text='Condição final do animal após período de observação.', max_length=1, null=True, verbose_name='Condição final do animal')),
                ('tp_interrupcao_tratamento', models.CharField(blank=True, choices=[('1', 'Sim'), ('2', 'Não')], help_text='Informa se o tratamento foi interrompido.', max_length=1, null=True, verbose_name='Houve interrupção do tratamento')),
                ('tp_motivo_interrupcao', models.CharField(blank=True, choices=[('1', 'Indicação da Unidade de saúde'), ('2', 'Abandono'), ('3', 'Transferência')], help_text='Motivo da interrupção do tratamento.', max_length=1, null=True, verbose_name='Motivo da interrupção')),
                ('tp_abandono_tratamento', models.CharField(blank=True, choices=[('1', 'Sim'), ('2', 'Não')], help_text='Informa se a unidade de saúde, em caso de abandono, fez busca-ativa do paciente.', max_length=1, null=True, verbose_name='Unidade procurou o paciente')),
                ('st_adverso_vacina', models.CharField(blank=True, choices=[('1', 'Sim'), ('2', 'Não'), ('9', 'Ignorado')], help_text='Informa se houve reação adversa à vacina.', max_length=1, null=True, verbose_name='Evento adverso à vacina')),
                ('st_soro_antirabico', models.CharField(blank=True, choices=[('1', 'Sim'), ('2', 'Não'), ('9', 'Ignorado')], help_text='Informa se houve indicação da aplicação do soro anti-rábico.', max_length=1, null=True, verbose_name='Indicação do soro anti-rábico')),
                ('nu_peso_paciente', models.SmallIntegerField(blank=True, help_text='Peso do paciente em quilogramas.', null=True, verbose_name='Peso do paciente (kg)')),
                ('qt_soro', models.SmallIntegerField(blank=True, help_text='Quantidade de soro aplicada em mililitros.', null=True, verbose_name='Quantidade de soro aplicada (ml)')),
                ('tp_soro', models.CharField(blank=True, choices=[('1', 'Heterólogo'), ('2', 'Homólogo')], help_text='Tipo de soro aplicado (heterólogo ou homólogo).', max_length=1, null=True, verbose_name='Tipo de soro')),
                ('tp_infiltracao_soro_total', models.CharField(blank=True, choices=[('1', 'Sim'), ('2', 'Não'), ('9', 'Ignorado')], help_text='Informa se houve infiltração total do soro nos ferimentos.', max_length=1, null=True, verbose_name='Infiltração de soro - Total')),
                ('tp_infiltracao_soro_parcial', models.CharField(blank=True, choices=[('1', 'Sim'), ('2', 'Não'), ('9', 'Ignorado')], help_text='Informa se houve infiltração parcial do soro nos ferimentos.', max_length=1, null=True, verbose_name='Infiltração de soro - Parcial')),
                ('tp_produtor_soro_antibico', models.CharField(blank=True, choices=[('1', 'Instituto Butantan'), ('2', 'Instituto Vital Brasil'), ('3', 'Aventis Pasteur'), ('4', 'Outro')], help_text='Laboratório produtor do soro anti-rábico utilizado.', max_length=1, null=True, verbose_name='Laboratório produtor do soro')),
                ('ds_produtor_soro_antibico', models.CharField(blank=True, help_text='Especificar outro laboratório produtor do soro anti-rábico.', max_length=30, null=True, verbose_name='Outro produtor de soro (especificar)')),
                ('nu_partida', models.CharField(blank=True, help_text='Número da partida ou lote do soro anti-rábico utilizado.', max_length=10, null=True, verbose_name='Número da partida/lote do soro')),
                ('st_adverso_soro', models.CharField(blank=True, choices=[('1', 'Sim'), ('2', 'Não'), ('9', 'Ignorado')], help_text='Informa se houve reação adversa ao soro anti-rábico.', max_length=1, null=True, verbose_name='Evento adverso ao soro')),
                ('dt_encerramento', models.DateField(blank=True, help_text='Data do encerramento do caso. Deve ser >= data de atendimento e <= data atual.', null=True, verbose_name='Data do encerramento do caso')),
                ('nu_lote_vertical', models.CharField(blank=True, help_text='Identificador do lote de transferência vertical da investigação entre níveis do sistema.', max_length=7, null=True, verbose_name='Lote de transferência vertical')),
            ],
            options={
                'verbose_name': 'Atendimento Anti-rábico',
                'verbose_name_plural': 'Atendimentos Anti-rábico',
                'db_table': 'atendimento_antirabico',
                'ordering': ['-created_date'],
            },
        ),
    ]
