# Generated by Django 6.0.4 on 2026-04-29 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Esquistossomose',
            fields=[
                ('id', models.BigAutoField(help_text='Chave primária do registro', primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Código de identificação do registro', max_length=10, verbose_name='Código')),
                ('created_date', models.DateTimeField(auto_now_add=True, help_text='Timestamp de criação do registro', verbose_name='Data de criação')),
                ('created_by', models.CharField(help_text='Usuário que criou o registro', max_length=256, verbose_name='Criado por')),
                ('last_modified_date', models.DateTimeField(auto_now=True, help_text='Timestamp da última modificação do registro', verbose_name='Data de última modificação')),
                ('last_modified_by', models.CharField(help_text='Usuário que realizou a última modificação', max_length=256, verbose_name='Modificado por')),
                ('status', models.CharField(help_text='Status do registro', max_length=20, verbose_name='Status')),
                ('dt_investigacao', models.DateField(help_text='Data em que ocorreu a investigação (1ª visita ao portador). Deve ser >= data da notificação.', verbose_name='Data da investigação')),
                ('co_cbo_ocupacao', models.CharField(blank=True, help_text='Código CBO da ocupação exercida pelo paciente.', max_length=6, null=True, verbose_name='Ocupação (CBO)')),
                ('dt_coproscopia', models.DateField(help_text='Data de realização da coproscopia. Deve ser >= data do diagnóstico.', verbose_name='Data da coproscopia')),
                ('nu_kato_katz', models.SmallIntegerField(blank=True, help_text='Número de ovos encontrados no exame Kato-Katz. 0 (zero) ou 1 (um) ou mais ovos.', null=True, verbose_name='Número de ovos (Kato-Katz)')),
                ('st_hoffman', models.CharField(blank=True, choices=[('1', 'Positivo'), ('2', 'Negativo'), ('3', 'Não realizado')], help_text='Resultado do exame Hoffman (positivo, negativo ou não realizado).', max_length=1, null=True, verbose_name='Exame Hoffman')),
                ('st_outro', models.CharField(blank=True, choices=[('1', 'Positivo'), ('2', 'Negativo'), ('3', 'Não realizado')], help_text='Resultado de outros exames (positivo, negativo ou não realizado).', max_length=1, null=True, verbose_name='Outros exames')),
                ('ds_exame_outro', models.CharField(blank=True, help_text='Nome do outro exame realizado. Habilitado se campo 36 diferente de 3 (não realizado).', max_length=40, null=True, verbose_name='Outros exames (especificar)')),
                ('tp_tratamento', models.CharField(choices=[('1', 'Sim, Praziquantel'), ('2', 'Sim, Oxaminiuine'), ('3', 'Não'), ('9', 'Ignorado')], help_text='Se o paciente fez tratamento para esquistossomose.', max_length=1, verbose_name='Fez tratamento')),
                ('dt_tratamento', models.DateField(blank=True, help_text='Data do tratamento. Obrigatório se tratamento = 1 ou 2.', null=True, verbose_name='Data do tratamento')),
                ('tp_nao_tratamento', models.CharField(blank=True, choices=[('1', 'Contra-indicação'), ('2', 'Recusa'), ('3', 'Ausente'), ('9', 'Ignorado')], help_text='Motivo quando tratamento = 3 (Não).', max_length=1, null=True, verbose_name='Motivo da não realização do tratamento')),
                ('st_cura_afirmativo_1', models.CharField(blank=True, choices=[('0', '0 (zero)'), ('1', '1 ou mais'), ('2', 'Não realizado')], help_text='Resultado da 1ª amostra para verificação de cura.', max_length=1, null=True, verbose_name='Verificação de cura - 1ª amostra')),
                ('st_cura_afirmativo_2', models.CharField(blank=True, choices=[('0', '0 (zero)'), ('1', '1 ou mais'), ('2', 'Não realizado')], help_text='Resultado da 2ª amostra para verificação de cura.', max_length=1, null=True, verbose_name='Verificação de cura - 2ª amostra')),
                ('st_cura_afirmativo_3', models.CharField(blank=True, choices=[('0', '0 (zero)'), ('1', '1 ou mais'), ('2', 'Não realizado')], help_text='Resultado da 3ª amostra para verificação de cura.', max_length=1, null=True, verbose_name='Verificação de cura - 3ª amostra')),
                ('dt_resultado_amostra3', models.DateField(blank=True, help_text='Data do resultado da 3ª amostra. Obrigatório se resultado = 0 ou 1.', null=True, verbose_name='Data do resultado da 3ª amostra')),
                ('tp_anatomo_clinica', models.CharField(blank=True, choices=[('1', 'Intestinal'), ('2', 'Hepato intestinal'), ('3', 'Hepato esplênica'), ('4', 'Aguda'), ('5', 'Outra')], help_text='Classificação da forma anátomo-clínica da esquistossomose.', max_length=1, null=True, verbose_name='Forma clínica')),
                ('ds_anatomo_clinica_outro', models.CharField(blank=True, help_text='Especificação quando forma clínica = 5 (Outra).', max_length=30, null=True, verbose_name='Outra forma clínica (especificar)')),
                ('tp_autoctone_residencia', models.CharField(choices=[('1', 'Sim'), ('2', 'Não'), ('3', 'Indeterminado')], help_text='Indica se o caso é autóctone do município de residência.', max_length=1, verbose_name='Caso autóctone do município de residência')),
                ('co_uf_infeccao', models.CharField(blank=True, help_text='Unidade Federada provável da fonte de infecção.', max_length=2, null=True, verbose_name='UF provável da infecção')),
                ('co_pais_infeccao', models.CharField(blank=True, help_text='País provável da fonte de infecção.', max_length=4, null=True, verbose_name='País provável da infecção')),
                ('co_municipio_infeccao', models.CharField(blank=True, help_text='Município provável da fonte de infecção.', max_length=6, null=True, verbose_name='Município provável da infecção')),
                ('co_distrito_infeccao', models.CharField(blank=True, help_text='Distrito provável da fonte de infecção.', max_length=4, null=True, verbose_name='Distrito provável da infecção')),
                ('co_bairro_infeccao', models.CharField(blank=True, help_text='Código do bairro provável da fonte de infecção.', max_length=8, null=True, verbose_name='Código do bairro provável da infecção')),
                ('no_bairro_infeccao', models.CharField(blank=True, help_text='Nome do bairro provável da fonte de infecção.', max_length=60, null=True, verbose_name='Bairro provável da infecção')),
                ('no_propriedade_infeccao', models.CharField(blank=True, help_text='Nome da propriedade onde ocorreu a transmissão, se área rural.', max_length=100, null=True, verbose_name='Nome da propriedade (área rural)')),
                ('no_colecao_infeccao', models.CharField(blank=True, help_text='Nome da coleção hídrica onde ocorreu a transmissão.', max_length=100, null=True, verbose_name='Nome da coleção hídrica')),
                ('st_doenca_trabalho', models.CharField(blank=True, choices=[('1', 'Sim'), ('2', 'Não'), ('9', 'Ignorado')], help_text='Se o caso está relacionado ao trabalho.', max_length=1, null=True, verbose_name='Doença relacionada ao trabalho')),
                ('tp_evolucao_caso', models.CharField(blank=True, choices=[('1', 'Cura'), ('2', 'Não Cura'), ('3', 'Óbito por esquistossomose'), ('4', 'Óbito por outras causas'), ('9', 'Ignorado')], help_text='Evolução do caso.', max_length=1, null=True, verbose_name='Evolução do caso')),
                ('dt_obito', models.DateField(blank=True, help_text='Data do óbito. Obrigatório se evolução = 3 ou 4. Deve ser >= data dos primeiros sintomas.', null=True, verbose_name='Data do óbito')),
                ('dt_encerramento', models.DateField(blank=True, help_text='Data do encerramento do caso. Deve ser >= data da investigação.', null=True, verbose_name='Data do encerramento')),
                ('nu_lote_vertical', models.CharField(blank=True, help_text='Identificador do lote de transferência vertical da investigação entre níveis do sistema.', max_length=7, null=True, verbose_name='Lote de transferência vertical')),
            ],
            options={
                'verbose_name': 'Esquistossomose',
                'verbose_name_plural': 'Esquistossomose',
                'db_table': 'esquistossomose',
                'ordering': ['-created_date'],
            },
        ),
    ]
