# Generated by Django 6.0.4 on 2026-04-29 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hanseniase',
            fields=[
                ('id', models.BigAutoField(help_text='Chave primária do registro', primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Código de identificação do registro', max_length=10, verbose_name='Código')),
                ('created_date', models.DateTimeField(auto_now_add=True, help_text='Timestamp de criação do registro', verbose_name='Data de criação')),
                ('created_by', models.CharField(help_text='Usuário que criou o registro', max_length=256, verbose_name='Criado por')),
                ('last_modified_date', models.DateTimeField(auto_now=True, help_text='Timestamp da última modificação do registro', verbose_name='Data de última modificação')),
                ('last_modified_by', models.CharField(help_text='Usuário que realizou a última modificação', max_length=256, verbose_name='Modificado por')),
                ('status', models.CharField(help_text='Status do registro', max_length=20, verbose_name='Status')),
                ('ds_prontuario', models.CharField(blank=True, help_text='Número/caractere atribuído pela unidade de saúde - identificador do prontuário.', max_length=10, null=True, verbose_name='Nº de prontuário')),
                ('co_cbo_ocupacao', models.CharField(blank=True, help_text='Código CBO da ocupação exercida pelo paciente.', max_length=6, null=True, verbose_name='Ocupação (CBO)')),
                ('nu_lesao_cultanea', models.SmallIntegerField(blank=True, help_text='Número de lesões dermatológicas apresentadas pelo paciente por ocasião do diagnóstico.', null=True, verbose_name='Nº de lesões cutâneas')),
                ('tp_forma_clinica', models.CharField(blank=True, choices=[('1', 'I - Indeterminada'), ('2', 'T - Tuberculóide'), ('3', 'D - Dimorfa'), ('4', 'V - Virchowiana'), ('5', 'Não classificado')], help_text='Forma clínica inicial por ocasião do diagnóstico, segundo classificação de Madrid.', max_length=1, null=True, verbose_name='Forma clínica')),
                ('tp_classific_operacional', models.CharField(choices=[('1', 'PB - Paucibacilar'), ('2', 'MB - Multibacilar')], help_text='Classificação operacional, por ocasião do diagnóstico, para eleição do esquema terapêutico.', max_length=1, verbose_name='Classificação operacional')),
                ('nu_nervo_afetado', models.SmallIntegerField(blank=True, help_text='Número de nervos afetados.', null=True, verbose_name='Nº de nervos afetados')),
                ('tp_incapacidade_fisica', models.CharField(blank=True, choices=[('0', 'Grau zero'), ('1', 'Grau I'), ('2', 'Grau II'), ('3', 'Não avaliado')], help_text='Avaliação do grau de incapacidade física por ocasião do diagnóstico.', max_length=1, null=True, verbose_name='Grau de incapacidade física no diagnóstico')),
                ('tp_modo_entrada', models.CharField(choices=[('1', 'Caso novo'), ('2', 'Transferência do mesmo município (outra unidade)'), ('3', 'Transferência de outro município (mesma UF)'), ('4', 'Transferência de outro estado'), ('5', 'Transferência de outro país'), ('6', 'Recidiva'), ('7', 'Outros reingressos'), ('9', 'Ignorado')], help_text='Modo de entrada do paciente no sistema.', max_length=1, verbose_name='Modo de entrada')),
                ('tp_caso_novo', models.CharField(blank=True, choices=[('1', 'Encaminhamento'), ('2', 'Demanda espontânea'), ('3', 'Exame de coletividade'), ('4', 'Exame de contatos'), ('5', 'Outros modos'), ('9', 'Ignorado')], help_text='Modo de detecção do caso novo. Habilitado quando modo de entrada = 1.', max_length=1, null=True, verbose_name='Modo de detecção de caso novo')),
                ('tp_baciloscopia', models.CharField(blank=True, choices=[('1', 'Positiva'), ('2', 'Negativa'), ('3', 'Não realizada'), ('9', 'Ignorado')], help_text='Resultado da baciloscopia.', max_length=1, null=True, verbose_name='Baciloscopia')),
                ('dt_ini_tratamento', models.DateField(blank=True, help_text='Data do início do tratamento. Deve ser >= data do diagnóstico.', null=True, verbose_name='Data do início do tratamento')),
                ('tp_esquema_terapeutico', models.CharField(blank=True, choices=[('1', 'PQT/PB/6 doses'), ('2', 'PQT/MB/12 doses'), ('3', 'Outros Esquemas Substitutos')], help_text='Esquema terapêutico inicial.', max_length=1, null=True, verbose_name='Esquema terapêutico inicial')),
                ('nu_contato_registrado', models.SmallIntegerField(blank=True, help_text='Número de pessoas que residam ou tenham residido, nos últimos 5 anos com o doente, a contar da data do diagnóstico.', null=True, verbose_name='Nº de contatos registrados')),
                ('st_importado', models.CharField(blank=True, editable=False, help_text='Identifica se o registro é oriundo da rotina de migração da base Windows.', max_length=2, null=True, verbose_name='Registro migrado')),
                ('co_uf_atual', models.CharField(blank=True, help_text='Sigla da UF onde está localizada a unidade de saúde responsável pelo tratamento atual do paciente.', max_length=2, null=True, verbose_name='UF de atendimento atual')),
                ('co_municipio_atual', models.CharField(blank=True, help_text='Código do município onde está localizada a unidade de saúde responsável pelo tratamento atual.', max_length=6, null=True, verbose_name='Município de atendimento atual')),
                ('nu_notificacao_atual', models.CharField(blank=True, help_text='Número da ficha de notificação/investigação enviada pela unidade de saúde atualmente responsável pelo paciente.', max_length=7, null=True, verbose_name='Número de notificação atual')),
                ('dt_notificacao_atual', models.DateField(blank=True, help_text='Data de notificação do caso pela unidade de saúde responsável pelo tratamento atual do caso.', null=True, verbose_name='Data de notificação atual')),
                ('co_unidade_atual', models.CharField(blank=True, help_text='Código CNES da unidade de saúde responsável pelo tratamento atual do paciente.', max_length=7, null=True, verbose_name='Unidade de atendimento atual (CNES)')),
                ('co_uf_residencia_atual', models.CharField(blank=True, help_text='Sigla da UF de residência atual do paciente.', max_length=2, null=True, verbose_name='UF de residência atual')),
                ('co_municipio_residencia_atual', models.CharField(blank=True, help_text='Código IBGE do município de residência atual do paciente.', max_length=6, null=True, verbose_name='Município de residência atual')),
                ('nu_cep_residencia_atual', models.CharField(blank=True, help_text='Código postal da residência atual do paciente.', max_length=8, null=True, verbose_name='CEP')),
                ('co_bairro_residencia_atual', models.DecimalField(blank=True, decimal_places=0, help_text='Código do bairro de residência atual do paciente.', max_digits=8, null=True, verbose_name='Código do bairro de residência atual')),
                ('no_bairro_residencia_atual', models.CharField(blank=True, help_text='Nome do bairro de residência atual do paciente.', max_length=60, null=True, verbose_name='Bairro de residência atual')),
                ('dt_ultimo_comparecimento', models.DateField(blank=True, help_text='Data do último comparecimento do paciente na unidade de saúde ou atendimento por agente de saúde. Deve ser >= data do início do tratamento.', null=True, verbose_name='Data do último comparecimento')),
                ('tp_classific_operacao_atual', models.CharField(blank=True, choices=[('1', 'PB - Paucibacilar'), ('2', 'MB - Multibacilar')], help_text='Classificação operacional do caso para eleição do esquema terapêutico adequado.', max_length=1, null=True, verbose_name='Classificação operacional atual')),
                ('tp_incapacidade_fisica_cura', models.CharField(blank=True, choices=[('0', 'Grau zero'), ('1', 'Grau I'), ('2', 'Grau II'), ('3', 'Não avaliado')], help_text='Avaliação do grau de incapacidade física no momento da cura.', max_length=1, null=True, verbose_name='Avaliação de incapacidade física na cura')),
                ('tp_esquema_terapeutico_atual', models.CharField(blank=True, choices=[('1', 'PQT/PB/6 doses'), ('2', 'PQT/MB/12 doses'), ('3', 'Outros Esquemas Substitutos')], help_text='Esquema terapêutico em uso.', max_length=1, null=True, verbose_name='Esquema terapêutico atual')),
                ('nu_dose_recebida', models.SmallIntegerField(blank=True, help_text='Número de doses supervisionadas recebidas sob supervisão.', null=True, verbose_name='Número de doses supervisionadas')),
                ('tp_reacao_tratamento', models.CharField(blank=True, choices=[('1', 'Reação tipo 1'), ('2', 'Reação tipo 2'), ('3', 'Reação tipo 1 e 2')], help_text='Tipo de reação apresentada pelo paciente durante tratamento da hanseníase.', max_length=1, null=True, verbose_name='Episódio reacional durante o tratamento')),
                ('dt_mudanca_esquema', models.DateField(blank=True, help_text='Data de mudança de esquema terapêutico (se pertinente).', null=True, verbose_name='Data de mudança do esquema')),
                ('nu_contato_examinado', models.SmallIntegerField(blank=True, help_text='Número de contatos intradomiciliares submetidos a exame dermatoneurológico. Deve ser <= número de contatos registrados.', null=True, verbose_name='Número de contatos examinados')),
                ('tp_alta', models.CharField(blank=True, choices=[('1', 'Cura'), ('2', 'Transferência p/ mesmo município'), ('3', 'Transferência p/ outro município'), ('4', 'Transferência p/ outro Estado'), ('5', 'Transferência p/ outro país'), ('6', 'Óbito'), ('7', 'Abandono'), ('8', 'Erro diagnóstico'), ('9', 'Transferência não especificada')], help_text='Tipo de saída/alta do paciente.', max_length=1, null=True, verbose_name='Tipo de saída')),
                ('dt_alta', models.DateField(blank=True, help_text='Data da alta. Deve ser >= data de início de tratamento.', null=True, verbose_name='Data da alta')),
                ('st_vincula', models.CharField(blank=True, choices=[('0', 'Não Vinculada'), ('1', 'Vinculada')], editable=False, help_text='Indica se a notificação foi vinculada.', max_length=1, null=True, verbose_name='Vinculação')),
                ('nu_lote_vertical', models.CharField(blank=True, help_text='Identificador do lote de transferência vertical da investigação e acompanhamento entre níveis do sistema.', max_length=7, null=True, verbose_name='Lote de transferência vertical')),
            ],
            options={
                'verbose_name': 'Hanseníase',
                'verbose_name_plural': 'Hanseníase',
                'db_table': 'hanseniase',
                'ordering': ['-created_date'],
            },
        ),
    ]
